name: asistente_transito
description: App m贸vil que permite interactuar con documentos mediante IA sin conexi贸n a internet.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Estado y DI
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.0
  
  # Almacenamiento local
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.1
  
  # Procesamiento de documentos
  pdf: ^3.10.4
  flutter_document_picker: ^5.2.3
  file_picker: ^5.5.0
  
  # FFI para c贸digo nativo
  ffi: ^2.1.0
  
  # Visualizaci贸n y UI
  flutter_markdown: ^0.6.18
  google_fonts: ^5.1.0
  fl_chart: ^0.65.0
  
  # Utilidades
  http: ^1.1.0
  intl: ^0.18.1
  equatable: ^2.0.5
  uuid: ^3.0.7
  logger: ^2.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.0
  isar_generator: ^3.1.0
  ffigen: ^9.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/embedding/
    - assets/models/llm/