name: asistente_transito
description: App móvil con IA offline para consulta de documentos

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Estado y DI
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.3.0
  
  # Almacenamiento local
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.1
  
  # Procesamiento de documentos
  pdf: ^3.10.4
  flutter_document_picker: ^5.2.3
  syncfusion_flutter_pdf: ^23.2.7
  docx_parser: ^0.1.0
  
  # FFI para código nativo
  ffi: ^2.1.0
  
  # Utilidades
  http: ^1.1.0
  intl: ^0.18.1
  equatable: ^2.0.5
  logger: ^2.0.2
  uuid: ^4.1.0
  flutter_markdown: ^0.6.18
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.5
  isar_generator: ^3.1.0
  custom_lint: ^0.5.3
  riverpod_lint: ^2.3.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/models/embedding/
    - assets/models/llm/